name       : dogtail
version    : 0.9.10
release    : 5
source     :
    - https://files.pythonhosted.org/packages/86/cd/3cc8dae75602ed13cde989e91ff22f759e829342b64e94975d73852518ec/dogtail-0.9.10.tar.gz : 55f01dffeff41293d92806d37bf00c08de430cbbc47badbbd92c31db08ceed4f
license    : GPL-2.0
component  : programming
summary    : dogtail is a GUI test tool and automation framework written in Python.
description: |
    dogtail is a GUI test tool and automation framework written in Python.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-cairo
    - python-gobject
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
