name       : dogtail
version    : 0.9.11
release    : 9
source     :
    - https://gitlab.com/dogtail/dogtail/raw/released/dogtail-0.9.11.tar.gz : 801a15b183916df5adadd50338e82f76426b5b598477d2dc5e2258b1ce47236b
license    : GPL-2.0-only
homepage   : https://gitlab.com/dogtail/dogtail/
component  : programming.tools
summary    : dogtail is a GUI test tool and automation framework written in Python
description: |
    GUI test tool and automation framework that uses assistive technologies to communicate with desktop applications.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pyatspi2
    - python3-cairo
    - python-gobject
build      : |
    %python3_setup
install    : |
    %python3_install
